- 해당 페이지 수행해봄! 
    - https://psystat.tistory.com/114 
    - https://github.com/sharebook-kr/pykrx

In [1]:
from pykrx import stock

### 2.1 종목코드 조회

In [5]:
# KOSPI / KODEX / KONEX 종목코드 조회
stock_code = stock.get_market_ticker_list(date="20210701",market="ALL")

In [6]:
# KOSPI 종목코드 조회 
stock_code = stock.get_market_ticker_list(date="20210701", market="KOSPI")

In [7]:
# 종목명 반환 
stock_name = stock.get_market_ticker_name("005930")
stock_name

'삼성전자'

### 2.2 일자별 OHLCV(시가, 고가, 저가, 종가, 거래량) 조회

In [8]:
df = stock.get_market_ohlcv_by_date(fromdate="20210501",todate="20210601",ticker="005930")

In [9]:
df

               시가     고가     저가     종가       거래량
날짜
2021-05-03  81000  82400  81000  81700  15710336
2021-05-04  81900  82600  81800  82600  12532550
2021-05-06  81700  82300  81700  82300  17047511
2021-05-07  81800  82100  81500  81900  14154882
2021-05-10  82300  83500  81800  83200  19385027
2021-05-11  82500  82600  81100  81200  28996680
2021-05-12  80800  81200  79800  80000  35812268
2021-05-13  78900  79600  78400  78500  31490096
2021-05-14  79000  80300  78900  80100  16450920
2021-05-17  80800  80900  79200  79600  17740855
2021-05-18  79600  80000  79100  79600  17494407
2021-05-20  79400  79700  79100  79500  16541828
2021-05-21  80100  81500  79800  80100  20961714
2021-05-24  80100  80400  79500  79700  13398666
2021-05-25  80000  80400  79800  79900  13628942
2021-05-26  80400  80500  79700  79800  11984359
2021-05-27  80000  80000  79100  79600  23198510
2021-05-28  79800  80400  79400  80100  12360199
2021-05-31  80300  80600  79600  80500  13321324
2021-06-01  80500  81300  80100  80600  14058401

- 한번에 많은 종목을 조회하면 ip가 차단될 수 있기 때문에, 반복문을 돌명서 사용할 때는 time 모듈로 sleep을 걸어주는 것이 좋음

### 2.3 특정일자의 전체종목 시세 조회

In [10]:
df = stock.get_market_ohlcv_by_ticker(date="20210520")
df.head()

            시가      고가      저가      종가      거래량         거래대금   등락률
티커
095570    6150    6160    5760    5820   253202   1492626480 -5.98
006840   34800   35100   33900   35000    65749   2276759650  1.16
027410    6810    6880    6770    6820   262941   1787892060 -0.87
282330  178000  182000  175000  178000    37376   6621394500 -2.20
138930    8020    8090    7900    7960  1861401  14829564980 -1.49

In [12]:
df = stock.get_market_ohlcv_by_ticker(date="20210701",market="KOSPI")
df.head()

            시가      고가      저가      종가      거래량         거래대금   등락률
티커
095570    6090    6090    5930    6000    57002    342327550 -1.32
006840   32900   33050   32050   32750    27937    913926300  0.46
027410    6660    6680    6540    6560   384905   2534130390 -1.50
282330  177500  178000  166500  170000   131003  22243998000 -5.29
138930    7750    7750    7610    7650  1222237   9341358220 -1.03

### 2.4 모든 종목의 가격 변동 조회

In [23]:
from pykrx import stock 
df = stock.get_market_price_change_by_ticker(fromdate="20210501",todate="20210520")
df.loc[df.종목명=="카카오",:]

        종목명      시가      종가  변동폭  등락률       거래량           거래대금
티커
035720  카카오  113500  113500    0  0.0  28524260  3220227496460

### 2.5 특정일자의 종목별 DIV/BPS/PER/EPS 조회

- DIV (배당수익률) : (주가배당금 / 주가) * 100
- BPS (주당순자산가치=청산가치) : 순자산 / 총발행주식수
- PER (주가수익비율) : 주가 / 주당순이익 
- EPS (주당순이익) : 당기순이익 / 총발행주식수 
- PBR (주가순자산비율) = 주가 / BPS = PER*EPS / BPS

In [24]:
df = stock.get_market_fundamental_by_ticker(date="20210707")
df.head()

          BPS       PER       PBR   EPS       DIV   DPS
티커
095570   6089   0.00000  1.000000     0  3.470703   210
006840  50471   0.00000  0.620117     0  1.280273   400
027410  15781  22.53125  0.409912   285  1.709961   110
282330  40317  23.65625  4.171875  7103  1.429688  2400
138930  26781   5.03125  0.280029  1498  4.250000   320

### 2.6 일자별 DIV / BPS / PER / EPS 조회

In [25]:
df = stock.get_market_fundamental_by_date(fromdate="20210701", todate="20210710",ticker="005930")
df.head()

              BPS    PER   PBR   EPS   DIV   DPS
날짜
2021-07-01  39406  20.85  2.03  3841  3.74  2994
2021-07-02  39406  20.83  2.03  3841  3.74  2994
2021-07-05  39406  20.93  2.04  3841  3.72  2994
2021-07-06  39406  21.14  2.06  3841  3.69  2994
2021-07-07  39406  21.04  2.05  3841  3.71  2994

- 나머지 여기 참고해서 좀 해봐야 겠다.. 
    - https://psystat.tistory.com/114

- 두가지 목표 
    - 웹사이트로 표현하기 
    - 실제 돈 벌수 있는 logic이 있어야함! 
        1. 외국인 매수비중 증가에 따른 상승예상 종목 확률 계산